// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AEmpty: typeof import('@arco-design/web-vue')['Empty']
    AResult: typeof import('@arco-design/web-vue')['Result']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
  }
}

export { }
